<?php
/**
 * BulkSetNumbersIntegrationSettingRequestModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Ringba
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * api.ringba.com
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.10
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Ringba;

/**
 * BulkSetNumbersIntegrationSettingRequestModelTest Class Doc Comment
 *
 * @category    Class
 * @description BulkSetNumbersIntegrationSettingRequestModel
 * @package     Ringba
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BulkSetNumbersIntegrationSettingRequestModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BulkSetNumbersIntegrationSettingRequestModel"
     */
    public function testBulkSetNumbersIntegrationSettingRequestModel()
    {
    }

    /**
     * Test attribute "number_ids"
     */
    public function testPropertyNumberIds()
    {
    }

    /**
     * Test attribute "conversion_set"
     */
    public function testPropertyConversionSet()
    {
    }

    /**
     * Test attribute "event_code"
     */
    public function testPropertyEventCode()
    {
    }

    /**
     * Test attribute "offline_upload_delay"
     */
    public function testPropertyOfflineUploadDelay()
    {
    }
}
