<?php
/**
 * ErrorSettingsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Ringba
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * api.ringba.com
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Ringba;

/**
 * ErrorSettingsTest Class Doc Comment
 *
 * @category    Class
 * @description ErrorSettings
 * @package     Ringba
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ErrorSettingsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ErrorSettings"
     */
    public function testErrorSettings()
    {
    }

    /**
     * Test attribute "dial_timeout_seconds"
     */
    public function testPropertyDialTimeoutSeconds()
    {
    }

    /**
     * Test attribute "ping_timeout_in_ms"
     */
    public function testPropertyPingTimeoutInMs()
    {
    }

    /**
     * Test attribute "call_on_failure"
     */
    public function testPropertyCallOnFailure()
    {
    }
}
