<?php
/**
 * ScheduleAndCapacityTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Ringba
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * api.ringba.com
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.10
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Ringba;

/**
 * ScheduleAndCapacityTest Class Doc Comment
 *
 * @category    Class
 * @description ScheduleAndCapacity
 * @package     Ringba
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ScheduleAndCapacityTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ScheduleAndCapacity"
     */
    public function testScheduleAndCapacity()
    {
    }

    /**
     * Test attribute "call_cap_matrix"
     */
    public function testPropertyCallCapMatrix()
    {
    }

    /**
     * Test attribute "call_concurrency_matrix"
     */
    public function testPropertyCallConcurrencyMatrix()
    {
    }

    /**
     * Test attribute "time_zone_id"
     */
    public function testPropertyTimeZoneId()
    {
    }

    /**
     * Test attribute "all_time_cap"
     */
    public function testPropertyAllTimeCap()
    {
    }

    /**
     * Test attribute "monthly_cap"
     */
    public function testPropertyMonthlyCap()
    {
    }

    /**
     * Test attribute "daily_cap"
     */
    public function testPropertyDailyCap()
    {
    }

    /**
     * Test attribute "hourly_cap"
     */
    public function testPropertyHourlyCap()
    {
    }

    /**
     * Test attribute "concurrency_cap"
     */
    public function testPropertyConcurrencyCap()
    {
    }

    /**
     * Test attribute "all_time_sum_cap"
     */
    public function testPropertyAllTimeSumCap()
    {
    }

    /**
     * Test attribute "monthly_sum_cap"
     */
    public function testPropertyMonthlySumCap()
    {
    }

    /**
     * Test attribute "daily_sum_cap"
     */
    public function testPropertyDailySumCap()
    {
    }

    /**
     * Test attribute "hourly_sum_cap"
     */
    public function testPropertyHourlySumCap()
    {
    }

    /**
     * Test attribute "hours_of_operation"
     */
    public function testPropertyHoursOfOperation()
    {
    }
}
