<?php
/**
 * CallLogApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Ringba
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * api.ringba.com
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Ringba;

use \Ringba\Configuration;
use \Ringba\ApiException;
use \Ringba\ObjectSerializer;

/**
 * CallLogApiTest Class Doc Comment
 *
 * @category Class
 * @package  Ringba
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CallLogApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for callLogExportCallLogs
     *
     * .
     *
     */
    public function testCallLogExportCallLogs()
    {
    }

    /**
     * Test case for callLogGetAvailableGroupBys
     *
     * .
     *
     */
    public function testCallLogGetAvailableGroupBys()
    {
    }

    /**
     * Test case for callLogGetEvents
     *
     * .
     *
     */
    public function testCallLogGetEvents()
    {
    }

    /**
     * Test case for callLogGetExportProgress
     *
     * .
     *
     */
    public function testCallLogGetExportProgress()
    {
    }

    /**
     * Test case for callLogGetLogsByDate
     *
     * .
     *
     */
    public function testCallLogGetLogsByDate()
    {
    }

    /**
     * Test case for callLogGetSearchField
     *
     * .
     *
     */
    public function testCallLogGetSearchField()
    {
    }

    /**
     * Test case for callLogGetSearchField_0
     *
     * .
     *
     */
    public function testCallLogGetSearchField0()
    {
    }

    /**
     * Test case for callLogGetSearchFields
     *
     * .
     *
     */
    public function testCallLogGetSearchFields()
    {
    }

    /**
     * Test case for callLogGetTagNames
     *
     * .
     *
     */
    public function testCallLogGetTagNames()
    {
    }

    /**
     * Test case for callLogGetTagTypes
     *
     * .
     *
     */
    public function testCallLogGetTagTypes()
    {
    }

    /**
     * Test case for callLogGetTagValues
     *
     * .
     *
     */
    public function testCallLogGetTagValues()
    {
    }
}
